---
title: "Vår ære og vår makt"
description: |
  Et utdrag (s. 67--71) fra Nordahl Greigs skuespill som ble uroppført på Den Nationale Scene i Bergen våren 1935. Tilgjengelig fra [Nasjonalbiblioteket](https://www.nb.no/items/2667596c7d945d1ef7e8a52482e83aac).
date: 2023-02-20
title-block-banner: "#b8e2f2"
editor_options: 
  chunk_output_type: console
---

ÅLESUND: Ka e det?

LUDVIGSEN: Det e presten. Han går rundt.

ÅLESUND: Ka for en båt e det som e gåen?

LUDVIGSEN: «Vargefjell».

ÅLESUND: Gikk der mange med?

LUDVIGSEN: Det ska eg ikkje kunne si.

MALVIN: Du ska ut igjen i kveld, Ålesund?

ÅLESUND: Ja, med «Blåeggen».

|     *(Present kommer ut igjen.)*

JOHANNE: Gikk der mange med?

| PRESTEN: Åtte omkom da skipet gikk under; seks frøs i hjel, for de var i livbåtene fem dager i kulde og hardt vær, før de kom til lands. Fire ble reddet.
|     *(Ser på listen)*
|     Kan noen si meg hvor Nøstesmuget 6 er, --- Berly Magnussen.

ÅLESUND: Det er like her nere.

PRESTEN: Takk, takk.

|     *(Han går videre.)*

JOHANNE: Å Herregud, ska han te Berly ---

|     *(Gråten tar henne. Andrea gråter også. Mennene står tause og bleke.)*

SKIPPER MEYDELL *(er kommet ut på sin trapp. Han er gammel, hvithåret, kraftig. Han skriker plutselig):* Det er spionene! Spionene har gjort det!

|     *(Ordene flammer i menneskene som petroleum på et ulmende bål.)*

ÅLESUND: Ja, det e spionene!

JOHANNE: Spionene har skylden!

MALVIN: Der e kanskje andre å gi skylden!

ÅLESUND: Kem?

MALVIN: De som sender oss ut.

SKIPPER MEYDELL *(hånlig):* Vet du ikkje at skibene *må* gå ut, for å skaffe oss det daglige brød!

MALVIN: Kor mange skib tror du det e som går med daglig brød, med korn og kull? Det e ikkje i *den* farten skibene våre går.

SKIPPER MEYDELL: Det blir vi tvunget te.

MALVIN: Men de tjener på det. *De.* Men vi som gjør jobben, kaslags liv, kaslags håp e det de gir oss?

| LUDVIGSEN: No ska du ikke være for urimelig heller, Malvin! Rederne kan være leie, det e sant og visst. Men *for tiden* i det ikkje nokke å si på de.
|     Eg e gammel i Junion. Eg husker alle de årene, kor tungt det var å slite seg te den minste rett.
|     No e det annerledes! Der e for eksempel aldri plønder med overtiden. Du får det du skriver opp Og de gir tillegg. Du får to kroner dagen for å gå i faresonen.

| SKIPPER MEYDELL *(forbitret):* Eg vet ikkje kem som e verst av dokker. Det e *nokken* ting som e for store te å handle med! To kroner meg her og to kroner meg der!
|     Vi tenkte ikkje sånn då eg var ung. Vi tenkte at det var stort å få vise flagget rundt jorden. Eg har vært skipper i femogtredve år, eg har sett folk stanse opp i havnene fra nord til syd, og ka va det de så? De så flagget. Då va eg stolt. Det var nok for meg.

| MALVIN: Eg har også sett flagget.
|     En av de gangene eg husker va ikkje lenge siden, ute i Atlanteren, vintersdag. Eg lå og svømte mellom vrakstumpene, og då såd eg flagget bli sudd ner, då akterskibet gukk under. Og eg har sett flagget nokken ganger te.
|     *(Langsomt og truende):*
|     Det e kanskje ikke riktig *at de bruker flagget mot oss*, at de slår oss ner med flagget, hver gang vi krever menneskeligere liv.
|     Men en dag ska vi ta flagget fra de. For de e *vårt* flagg.

| SKIPPER MEYDELL: Du kan spare deg ordene dine. For eg forstår deg, eg. Du ska ut igjen snart no.Det e et stygt ord det som eg no kommer å bruke; men eg bruker det allikevel.
|     Du e redd, du far!

| MALVIN *(smiler):* Eg tror du ska gå inn igjen til seilskutebildene dine og skibspartene som stiger så godt.
|     Redd. Ja, eg tror vi *ska* være redd for å dø, når vi ikkje mener det e riktig, det vi ska dø for.
|     Men der ska nokke te for å kjennes ved den redslen. Og du kan være rolig. Eg ska ut igjen.

ANDREA *(stillfarende, rolig i sin fortvilelse):* Der ser du. Selv går du ut. Ka ve du vi andre ska gjøre. Eg har mistet to gutter på sjøen siste året, no følger eg den yngste, han ska være messegutt på «Blåeggen». Ka ve du eg ska gjøre, Malvin?

SKIPPER MEYDELL: Drep spionene. Nokken e tatt, flere e igjen. De sier agent Olsen leder de *fra fengslet*. Konen hans er på fri fot, og sønnen hans.

JOHANNE: Gutten brukte de te alt ---

FØRSTE GUTT: Eg kjenner han ---

JOHANNE: Han gikk med teleframmer, så det ikkje skulle vekke mistanke ---

FØRSTE GUTT: Han fikk alt ka han ønsket seg, sykkel ---

ANNEN GUTT: Eg ville heller la være å ha sykkel, hvis eg va han ---

SKIPPER MEYDELL: Spionene har greie på alt. De har trådløse stasjoner! Vær sikker på at der e gått melding ta alle ubåtene at i natt går «Blåeggen».

ANDREA: Å, Herre Jesus ---

SKIPPER MEYDELL: De vet at i dette øyeblikket går dokker nerover bakken her ---

ANDREA: E her ikkje help å få ---

SKIPPER MEYDELL: Vi kan hade de, straffe de, utrydde de. Sette skrekk i de som enda ikkje e tatt. Jage de som rotte tilbake til hullene sine.

| (Oppe i hovedgaten ser vi Leif smyge seg bortover langs husveggen.)

FØRSTE GUTT: Der e Leifen.

JOHANNE: Sønnen til spionen!

SKIPPER MEYDELL: Den verste av de alle!

ANNEN GUTT: Han har et brev i hånden ---

ÅLESUND: Det e oss han e ute etter denne gangen!

FØRSTE GUTT: Det va han som fikk senket «Bordund» kor Ottoen var ombord ---

ANNEN GUTT: Det va han som drepte Sigurden ---

SKIPPER MEYDELL: Stans han!

FØRSTE GUTT: Stein han!

LEIF *(holder armen over det likbleke, dødsredde ansiktet, skriker):* Ikkje! Ikkje!

|     *(De kaster stein på ham.)*

FØRSTE GUTT: Så dokker! Den traff!

MALVIN *(kaster seg imellom dem):* Dokker e gale! Ve dokker drepe barnet!

|     *(Leif er flyktet nedover hovedgaten.)*

ANNEN GUTT: Så dokker han blødde ---

ÅLESUND *(skamfull):* E det bedre at *han* dreper oss?

|     *(Ditlef kommer gående oppover hovedgaten den motsatte veiein.)*

MALVIN: Ska dokker steine nokken, så stein heller han!

LUDVIGSEN: Kordan kan du si nokke sånt ---

ANDREA: Rett ska være rett, Malvin. Eg syr for frøken Berents som e hos han på kontoret. Hon sier han e et sjeldent menneske, et gjertemenneske, storartet mot barnene.

MALVIN: Men mot *oss* har han et hardere hjerte. Ka e det det heter? Et hjerte av gull.

DITLEF: Eg skjønner at her e elementer iblant oss som helst vil dekke over spionene. De om det. Eg ve bare si at te mitt siste åndedrag ve eg kjempe mot de som sender våre heltemodige sjøfolk til bunns.

ANDREA: Takk fordi De vil hjelpe oss ---

ÅLESUND *(ærbødig):* Ja, Dem herr skibsreder, takker vi for Deres mandige ord!
