project:
  type: website
  output-dir: docs

resources:
  - "favicon.png"
  - "CNAME"
  - ".nojekyll"
  - "resources/*"
  - "articles/*"
  - "presentations/*"

website:
  title: "Richard Aubrey White, Ph.D."
  site-url: "https://www.rwhite.no"
  favicon: favicon.png
  body-header: |
    <script data-goatcounter="https://rwhiteno.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
  navbar:
    title: "White, Ph.D."
    background: "#231c16"
    pinned: false
    left: []
    right:
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Presentations"
        href: presentations.qmd
      - text: "Writing"
        href: writing.qmd

format:
  html:
    theme: styles.scss
    anchor-sections: false
    link-external-newwindow: true
