---
title: "CV"
description: |
  Richard is an applied infectious diseases statistician based in Oslo, Norway. He is currently employed as the tech lead for [Sykdomspulsen](https://docs.sykdomspulsen.no), a real-time analysis and disease surveillance system based in the Norwegian Institute of Public Health (Folkehelseinstituttet). His international field experience includes developing and managing surveillance systems for Ebola in Sierra Leone, acute watery diarrhea/cholera in Mozambique, and maternal health in Palestine.
---

## Contact

hello@rwhite.no

## Education

**University of Bergen, Norway**

2022 - 2023 / One year program (Årsstudium) in Nordic languages and literature

**Harvard University, USA**

2011 - 2012 / Ph.D in Biostatistics

2009 - 2011 / MA in Biostatistics (Frank Knox fellowship)

**University of Wollongong, Australia**

2005 - 2009 / B. Maths (Advanced) Honours (Applied Statistics)

## Skills

- R (15+ years)
- STATA (10+ years)
- Docker (5+ years)
- CI/CD (5+ years)
- Python (1 year)
- Kubernetes (6 months)

## Languages

- English (Fluent)
- Norwegian (B2)

## Norwegian Institute of Public Health (NIPH/FHI)

### Technical Lead - Sykdomspulsen: Real-Time Surveillance

*07.2019 - now / Oslo, Norway*

<https://docs.sykdomspulsen.no>

-   Tech lead for Sykdomspulsen (8 person team), a real-time analysis and disease surveillance system. Complex statistical analyses are automatically run for all locations in Norway, producing reports and alerting various stakeholders.
-   Technology in use includes:
    -   Kubernetes.
    -   Docker/Podman.
    -   CI/CD (Jenkins/GoCD/ArgoCD).
    -   R/Python.
-   Surveils:
    -   All cause/cause-specific/attributable mortality.
    -   Vaccine associated mortality.
    -   Covid-19.
    -   Influenza.
    -   Tuberculosis.
    -   IPD.
    -   Meningococcal disease.
    -   Pertussis.
    -   Antibiotic use and healthcare associated infection.
    -   Gastritis.
-   Interactive website for municipal health authorities.
-   APIs for internal/external use.
-   1 000 000+ analyses per day.
-   1 000+ automatic reports (pdf/excel/email/sms) per day.

### Infectious Diseases Statistician - Infectious Disease Epidemiology

*06.2014 - 06.2019 / Oslo, Norway*

-   Advised outbreak teams, researchers, and students in statistical concepts, methods, and programming.
-   Developed surveillance reports (and all relevant infrastructure and code for signal processing) in the format of interactive websites for:
    -   Gastritis and upper-respiratory outbreaks using the syndromic surveillance registry.
    -   Outbreaks using the notifiable disease registry (MSIS).
    -   Excessive mortality using the death registry (DÅR).
-   Developed statistical protocol for a 20 000 person longitudinal study regarding Norwegian water usage.
-   Modelled the 2014 Ebola outbreak to estimate the likelihood of a case flying to Norway and the subsequent usefulness of entry screening in Oslo airport.
-   Modelled the burden of HCV in Norwegian people who inject drugs.
-   Statistician on the data monitoring committee (DMC) for the:
    -   PEEP RCT in Haydom, Tanzania.
    -   Safer Births Moyo RCT in Muhimbili, Tanzania.

### Statistician/Postdoc - Genes and Environment

*01.2012 - 05.2014 / Oslo, Norway*

-   Developed database management structures to allow for the construction of analysis datasets from multiple disparate sources (e.g. written questionnaires, lab toxicant concentrations, Illumina microbial data).
-   Investigated the relationship between seasonality, sunlight, and suicide.
-   Investigated the relationship between gun ownership and completed suicide in the US, highlighting the lack of method substitution where gun ownership is less prevalent.

## Médecins Sans Frontières (MSF)

### Statistician OCB

*10.2015 - now / Oslo, Norway*

-   Developed statistical protocol for a 10 000 person stepwise-RCT regarding DR-TB in a Mumbai slum.
-   Advised on surveillance methods to detect extreme malaria seasons in areas with low quality data.
-   Identified predictors of death amongst Ebola patients in a Guinean Ebola Treatment Unit.

## Norwegian Red Cross (NorCross)

### Community Based Surveillance Delegate

*04.2019 - 05.2019 / Beira, Sofala, Mozambique*

-   Responded to a cholera outbreak.
-   Managed a real-time surveillance system for people with diarrhea visiting Red Cross oral rehydration points as a part of the response to the cholera outbreak in Beira caused by Cyclone Idai.
-   Liaised with the MOH on issues of interest, such as serious cases of diarrhea and self-reported bloody diarrhea.

## Palestinian National Institute of Public Health (PNIPH)

### Statistician

*09.2017 - 09.2019 / Ramallah, West Bank, Palestine*

-   Trained local staff in data management and statistical programming for the national maternal and child health registry.
-   Used raw survey data to validate indicators from the newly formed national healthcare worker registry.

## World Health Organization (WHO)

### GIS Expert/Data Manager - Global Outbreak Alert and Response Network (GOARN)

*01.2015 - 02.2015 / Kambia, Sierra Leone*

-   Responded to an Ebola outbreak.
-   Developed and managed a real-time surveillance system for the Ebola outbreak in Kambia, linking the national emergency number, Ebola holding centers, Ebola community care centers, Ebola treatment centers, and burials.
-   Geocoded and mapped relevant outbreak data (alerts, cases, border crossings).
-   Generated daily sitreps using GIS data and epidemiological information from the surveillance database.
-   Trained and supervised international and national staff in the use of the Kambian Ebola surveillance system.

### Biostatistician - Mortality and Burden of Disease

*04.2011 - 11.2011 / Geneva, Switzerland*

-   Collected cause of death data from multiple national cause of death registries into a database and calculated avoidable mortality estimates for disease groups over time, comparing trends in high income versus developing countries.
-   Produced disease prevalence estimates for the Global Burden of Disease project (GBD 2010), most notably for vision loss, micronutrient deficiency, and osteoarthritis for all UN member nations, in all sex/age combinations, from 1990 to 2010.

### Biostatistician - Stop TB Department

*06.2010 - 11.2010 / Boston, USA*

-   Liaised with NGOs from South Africa, Uzbekistan, Bangladesh, and Peru to gain access to MDR-TB datasets, then managed, cleaned, and analysed the datasets.
-   Provided recommendations for the WHO Guidelines for the Programmatic Management of Drug Resistant Tuberculosis (3rd edition) via multi-cohort survival analyses to determine factors affecting detection of MDR-TB and survival in a programmatic context.
