---
title: "Palak Paneer"
description: |
  North Indian curry with paneer and spinach.
categories: [North India, Vegetarian]
title-block-banner: "#e2ebf0"
editor_options: 
  chunk_output_type: console
---

|    Metric    |   Value    |
|:------------:|:----------:|
|  Prep time   |   30min    |
| Cooking time |   45min    |
|    Serves    | Six people |

: Information

# Ingredients

|  **Purpose**  | **Ingredient**  | **Quantity** |
|:-------------:|:---------------:|:------------:|
|   Spice mix   |     Butter      |     50g      |
|               |    Fenugreek    |  1 teaspoon  |
|               |      Cumin      | 1 tablespoon |
|               |    Coriander    | 1 tablespoon |
|               |    Turmeric     | 1 tablespoon |
|               |     Garlic      |   4 cloves   |
|               |      Onion      |   1 piece    |
|               |                 |              |
|  **Purpose**  | **Ingredient**  | **Quantity** |
| Spinach puree |     Spinach     |     500g     |
|               |      Cream      |    200mL     |
|               |                 |              |
|  **Purpose**  | **Ingredient**  | **Quantity** |
| Main protein  | Paneer/Halloumi |     500g     |
|               |      Chili      | 1 tablespoon |
|               |                 |              |
|  **Purpose**  | **Ingredient**  | **Quantity** |
|    Garnish    |   Pomegranate   |   1 piece    |

# Instructions

## Pudding

1.  Sift together flour, bicarb soda, and salt.
2.  Beat sugar and eggs until light and fluffy.
3.  Add apricot jam and beat well.
4.  In a saucepan, melt the butter.
5.  Add the vinegar and milk.
6.  Fold in the flour and egg mixtures alternatively.
7.  Pour into a greased baking tray.
8.  Bake at 180C for 45 minutes.

## Sauce

1.  Place all ingredients into a saucepan.
2.  Stir over moderate heat until butter has melted and the sugar dissolved.
3.  Pierce pudding with skewer and pour sauce over hot pudding.

## Serving

1.  Garnish with fresh mint leaves.
2.  Serve hot or cold with cream or custard.
